### ISSUE TITLE
How to use this extension with AJAX?

### ISSUE THREAD

**Issue by DanielDanielDanielD** [uacaps/BootstrapNotifications#2]
I want to get any message from AJAX that go through BootstrapNotifications, how can I achieve it?

**so far this is my AJAX function:**
```
$.ajax({
        type: "POST",
        url: "/*****/******",
        data: { ***: ***},
        success: function () {
            ////// Here I want to leave the Notification message //////
        },
        error: function () {
            ////// Here I want to leave the Notification message //////
        }
    })
```

**Comment by MFFoX** [comment]
This library is specifically a controller extension so it doesn't cover client-side notification generation. 

My suggestion would be to write your own `notify()` javascript function or use a toaster library like https://github.com/CodeSeven/toastr.
